AMOUNT_OF_FIELDS = 10
AMOUNT_OF_GROUPS_IN_FIELD = [6, 8, 4, 2]
SUBJECTS_PER_FIELD = [8, 8, 7, 6]
AMOUNT_OF_STUDENTS_PER_GROUP = 8 * [30] + 2 * [15]
AMOUNT_OF_LECTURERS = 20
AMOUNT_OF_BUILDINGS = 4
DISTANCES_BETWEEN_BUILDINGS = 2 * [10] + 2 * [20]
AMOUNT_OF_LAB_ROOMS = [2, 1, 3, 1]
AMOUNT_OF_LECT_ROOMS = [2, 1, 3, 1]
LAB_ROOMS_CAPACITIES = [max(AMOUNT_OF_STUDENTS_PER_GROUP)]
LECTURE_ROOM_CAPACITIES = [
    max(AMOUNT_OF_GROUPS_IN_FIELD) * max(AMOUNT_OF_STUDENTS_PER_GROUP)]
AMOUNT_OF_RANDOM_UNAVAILABILITY_FOR_ROOMS = 10 * [0] + 2 * [1] + [2]
AMOUNT_OF_RANDOM_UNAVAILABILITY_FOR_LECTURERS = 5 * [0] + 5 * [1] + 4 * [2]
UNAVAILABILITY_DURATION_ROOMS = 4 * [60 * 4] + 2 * [60 * 8]
UNAVAILABILITY_DURATION_LECTURERS = 4 * [60 * 4] + 2 * [60 * 2]
DURATIONS_OF_CLASSES = 3 * [90] + [60, 120]
AVAILABLE_ROOMS_AMOUNT = 10 * [1] + 5 * [2] + 20 * [10]
